credentials:
  batch:
    account_service_url: https://REMOVED.eastus.batch.azure.com
    aad:
      directory_id: REMOVED
      application_id: REMOVED
      auth_key: REMOVED
  storage:
    mystorageaccount:
      account: REMOVED
      account_key: REMOVED
      endpoint: core.windows.net
  docker_registry:
    REMOVED.azurecr.io:
      username: REMOVED
      password: REMOVED
  monitoring:
    grafana:
      admin:
        username: admin
        password: REMOVED
  management:
    aad:
      authority_url: https://login.microsoftonline.com
      endpoint: https://management.azure.com/
      directory_id: REMOVED
      application_id: REMOVED
      auth_key: REMOVED
    subscription_id: REMOVED
